languageCode = "en-us"
baseURL = "https://thejsway.netlify.app/"
title = "The JS Way"

[params]
subtitle = "A gentle introduction to an essential language"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "paraiso-dark"
    tabWidth = 4
  [markup.goldmark.parser.attribute]
    block = true
    title = true

[outputs]
   home = [ "HTML", "JSON" ]